
import { GoogleGenAI } from "@google/genai";
import { ImageData } from "../types";

export const outfitSwap = async (target: ImageData, outfit: ImageData): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
  
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          inlineData: {
            data: target.base64.split(',')[1],
            mimeType: target.mimeType,
          },
        },
        {
          inlineData: {
            data: outfit.base64.split(',')[1],
            mimeType: outfit.mimeType,
          },
        },
        {
          text: "This is a high-fidelity outfit swap task. The first image contains a person. The second image contains a reference outfit. Generate a new version of the first image where the person is wearing the exact outfit from the second image. Maintain the person's pose, identity, and facial expression. The lighting and background should remain consistent and professional.",
        },
      ],
    },
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
    }
  }
  
  throw new Error("No image generated by the model.");
};

export const editImageWithText = async (image: ImageData, prompt: string): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
  
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          inlineData: {
            data: image.base64.split(',')[1],
            mimeType: image.mimeType,
          },
        },
        {
          text: `Please edit the provided image based on this instruction: "${prompt}". Return only the modified image.`,
        },
      ],
    },
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
    }
  }
  
  throw new Error("Editing failed.");
};
